name: upload

on:
  push:
    branches: [ t9z ]

jobs:
  build:
    runs-on: ubuntu-latest

    if: github.event.repository.owner.id == github.event.sender.id

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: t9z
     # - name: Sync to Gitee
     #   uses: wearerequired/git-mirror-action@master
     #   env:
     #       # 注意在 Settings->Secrets 配置 GITEE_RSA_PRIVATE_KEY
     #       SSH_PRIVATE_KEY: ${{ secrets.GITEE_RSA_PRIVATE_KEY }}
     #   with:
     #       # 注意替换为你的 GitHub 源仓库地址
     #       source-repo: "git@github.com:zerofo/zerofo.github.io.git"
     #       # 注意替换为你的 Gitee 目标仓库地址
     #       destination-repo: "git@gitee.com:zerofo/zerofo.git"

     # - name: Build Gitee Pages
     #   uses: yanglbme/gitee-pages-action@master
     #   with:
     #       # 注意替换为你的 Gitee 用户名
     #       gitee-username: zerofo
     #       # 注意在 Settings->Secrets 配置 GITEE_PASSWORD
     #       gitee-password: ${{ secrets.GITEE_PASSWORD }}
     #       # 注意替换为你的 Gitee 仓库
     #       gitee-repo: zerofo/zerofo
     #       branch: l672
            


      - name: cleanup & env setup
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo -E apt update
          sudo -E apt install git curl tar make libgcrypt-dev gcc srecord zip python3-pip gzip wget -y
          sudo -E pip3 install Cython
          sudo -E pip3 install BaiduPCS-Py
          sudo -E curl -fsSL https://raw.githubusercontent.com/arduino/arduino-cli/master/install.sh | sudo -E BINDIR=/bin sh
          sudo -E curl -sSLo mklittlefs.tar.gz https://github.com/earlephilhower/mklittlefs/releases/download/3.0.0/x86_64-linux-gnu-mklittlefs-295fe9b.tar.gz 
          sudo -E tar xfz mklittlefs.tar.gz -C /bin/ --strip-components=1
          sudo -E rm mklittlefs.tar.gz
          sudo -E arduino-cli config init 
          sudo -E arduino-cli config add board_manager.additional_urls http://arduino.esp8266.com/stable/package_esp8266com_index.json
          sudo -E arduino-cli config set library.enable_unsafe_install true
          sudo -E arduino-cli core install esp8266:esp8266
          sudo -E arduino-cli core upgrade
          sudo -E arduino-cli lib install --git-url https://github.com/me-no-dev/ESPAsyncTCP.git
          sudo -E arduino-cli lib install --git-url https://github.com/me-no-dev/ESPAsyncWebServer.git
          sudo -E arduino-cli lib upgrade
          sudo -E apt-get -y autoremove --purge
          sudo -E apt-get clean
          echo ${{ secrets.BD_USS }} | BaiduPCS-Py useradd --cookies ${{ secrets.BD_COOKIE }} --bduss ${{ secrets.BD_USS }}
      - name: build 
        run: |
          cd ../
          sudo -E git clone https://github.com/zerofo/docker-8266-builder
          sudo -E sed -i "s/ps4-zerofo/ps4-zerofo---t9z-900(U盘控制)----github自动上传版本---底包---v1.6.2xy---/g" ./docker-8266-builder/config.txt
          sudo -E cp ./docker-8266-builder/config.txt /config.txt
          sudo -E sed -i "s/compress\=y/compress\=n/g" /config.txt
          sudo -E sed -i "s/#blockList/blockList/g" /config.txt
          sudo -E cp ./docker-8266-builder/mk8266.sh /mk8266.sh
          sudo -E rm ./t9x/t9x.git -rf
          sudo -E cp ./t9x /mk8266 -rf
          sudo -E ls /mk8266
          sudo -E sed -i "s/网页版: 插入U盘.  (8266免插拔 请无视\!\!\!)//g" /mk8266/common/kexploit.js
          sudo -E rm /mk8266/README.md -rf
          sudo -E rm /mk8266/CNAME -rf
          sudo -E cp ./docker-8266-builder/Ps4-wifi-http_async /Ps4-wifi-http -rf
          sudo -E mkdir -p /output
          sudo -E bash /mk8266.sh
          sudo -E mkdir /900;
          sudo -E echo "zip file"
          sudo -E zip -r /900/zerofo_900.zip ./t9x -x"*/.git*"
          sudo -E echo "upload"
          if [ `cat t9x/.github/packup` -eq 1 ]; then sudo -E BaiduPCS-Py upload /output/*.zip /8266/8266固件包---bin/900/;sudo -E BaiduPCS-Py sync /900 /8266/网站_离线包/900/; else echo "此commit 不打包"; fi;
          
      - name: upload binfile
        uses: actions/upload-artifact@v2
        with:
          name: ps4-8266-bin------------github自动上传版本
          path: /output/
